apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
        - containerPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
spec:
  selector:
    app: flaresolverr
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8191
