apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
      - name: jellyfin-media
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
      - name: jellyfin-media2
        persistentVolumeClaim:
          claimName: jellyfin-media2-pvc
      - name: jellyfin-config
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: jellyfin-cache
        persistentVolumeClaim:
          claimName: jellyfin-cache-pvc
      containers:
      - name: jellyfin-container
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        imagePullPolicy: Always
        volumeMounts:
        - name: jellyfin-media
          mountPath: /media
        - name: jellyfin-config
          mountPath: /config
        - name: jellyfin-cache
          mountPath: /cache
        - name: jellyfin-media2
          mountPath: /media2
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8096


