apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-large2
  labels:
    type: media2
spec:
  capacity:
    storage: 465Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/sampi/persistent-volume-mount2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rpi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media2-pvc
spec:
  selector:
    matchLabels:
      type: media2
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 465Gi
