apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission2
  template:
    metadata:
      labels:
        app: transmission2
    spec:
      volumes:
      - name: jellyfin-media2
        persistentVolumeClaim:
          claimName: jellyfin-media2-pvc
      - name: transmission-config
        configMap:
          name: transmission-config
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:latest
        ports:
        - containerPort: 9091
        - containerPort: 51413
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Brazil/East"
        - name: USER
          value: "admin"
        - name: PASS
          value: "admin"
        volumeMounts:
        - name: jellyfin-media2
          mountPath: /downloads
        - name: transmission-config
          mountPath: /defaults
---
apiVersion: v1
kind: Service
metadata:
  name: transmission2-service
spec:
  selector:
    app: transmission2
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9091
    name: http
  - protocol: TCP
    port: 51413
    targetPort: 51413
    name: torrent
