apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
      - name: jellyfin-media2
        persistentVolumeClaim:
          claimName: jellyfin-media2-pvc
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: jellyfin-media2
          mountPath: /media
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8989
